<?php

declare(strict_types=1);

namespace OpenSolid\Core\Domain\Event\Message;

use OpenSolid\Bus\Envelope\Message;
use Symfony\Component\Uid\Uuid;

/**
 * Base class for domain events in the system.
 *
 * Domain events represent something meaningful that happened in the domain.
 * They are immutable records of past occurrences that other parts of the
 * system can react to.
 *
 * @extends Message<void>
 */
abstract readonly class DomainEvent extends Message
{
    /**
     * Unique identifier for this event instance (autogenerated).
     */
    public string $id;

    /**
     * Identifier of the aggregate that produced this event.
     */
    public string $aggregateId;

    /**
     * Timestamp when this event occurred (autogenerated).
     */
    public \DateTimeImmutable $occurredOn;

    public function __construct(string $aggregateId)
    {
        $this->id = Uuid::v7()::generate();
        $this->aggregateId = $aggregateId;
        $this->occurredOn = new \DateTimeImmutable();
    }
}
